docker run -d --name kafka-muezzin `
  -p 9095:9092 `
  -e ALLOW_PLAINTEXT_LISTENER=yes `
  -e KAFKA_BROKER_ID=1 `
  -e KAFKA_CFG_NODE_ID=1 `
  -e KAFKA_CFG_PROCESS_ROLES=broker,controller `
  -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9095 `
  -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-muezzin:9092 `
  -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER `
  -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-muezzin:9095 `
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT `
  bitnami/kafka:3.5


  docker run -d --name kafka-muezzin `
  -p 9093:9092 `
  -e ALLOW_PLAINTEXT_LISTENER=yes `
  -e KAFKA_BROKER_ID=1 `
  -e KAFKA_CFG_NODE_ID=1 `
  -e KAFKA_CFG_PROCESS_ROLES=broker,controller `
  -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 `
  -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-muezzin:9092 `
  -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER `
  -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-muezzin:9093 `
  -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT `
  bitnami/kafka:3.5